# SwiftLint default configuration

# Paths to ignore
excluded:
  - Pods
  - Carthage
  - .build

disabled_rules:
  - line_length
  - todo
  - file_length
  - identifier_name
  - type_name
  - multiple_closures_with_trailing_closure
  - unused_optional_binding

type_body_length:
  warning: 300
  error: 400

reporter: "github-actions-logging"
strict: true
